name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Проверка репозитория
      - name: Checkout code
        uses: actions/checkout@v3

      # Установка Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # Установка зависимостей
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Запуск тестов
      - name: Run unittests
        run: |
          python -m unittest discover -s . -p '*_test.py'

      # Удаление тестовой базы данных
      - name: Cleanup test database
        run: |
          if [ -f test_resources.db ]; then
            rm test_resources.db
          fi

